<div class=" container mt-4 text-center container_cadastrar" id="logo">
                <form method="post" action="/cadastrar" class="pt-5 border">
                    <div class="container">
                        <img src="/img/instagram.png" alt="instagram_logo" class="img-fluid" id="logo">
                        <p class="text-secondary pt-2">Cadastre-se para ver fotos e vídeos dos seus amigos.</p>
                        <hr class="pt-3">
                        <h6 class="text-secondary">OU</h6>
                    
                    </div>
                    <div class="container">
                        <div class="form-group pt-4">
                            <input type="text" name="numero_email" class="form-control" placeholder="Telefone ou e-mail" id="email">
                        </div>
                        <div class="form-group">
                            <input type="text" name="nome" class="form-control" placeholder="nome" id="pwd">
                        </div>
                        <div class="form-group">
                            <input type="text" name="usuario" class="form-control" placeholder="Nome do usuário" id="pwd">
                        </div>
                        <div class="form-group">
                            <input type="password" name="senha" class="form-control" placeholder="Senha" id="pwd">
                        </div>
    
                        <button class="btn btn-primary btn-block mb-2" >Cadastre-se</button>
                        
                        <small>Ao se cadastrar, você concorda com nossos Termos, Política de Dados e Política de Cookies.</small>
                    </div>
                </form>
                <div class="border mt-1 text-center">
                    <p class="py-2 ">Tem conta? <a href="/">Conecte-se</a></p>
                </div>

            </div>