<div class="container mt-5">
    <div class="container ml-5">
        <div class="row">
            <div class="col-6" id="celular">
                <img src="/img/celular.png" class="img-fluid" alt="celular">
            </div>
    
            <div class="col-5  mt-4 text-center " id="logo">
                <form method="post" action="" class="pt-5 border">
                    <div class="">
                        <img src="/img/instagram.png" alt="instagram_logo" class="img-fluid" id="logo">
                    </div>
                    <div class="container container_">
                        <div class="form-group pt-4">
                            <input type="email" class="form-control" placeholder="Telefone, nome de usuário ou e-mail" id="email">
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control" placeholder="Senha" id="pwd">
                        </div>
    
                        <button class="btn btn-primary btn-block" disabled>Entrar</button>

                        <p class="text-danger">Usuário ou senha incorretos</p>

                        <hr class="pt-3">
                        
                        <a href=""><p class="text-secondary">Esqueceu a senha?</p></a>
                    </div>
                </form>
                <div class="border mt-1 text-center">
                    <p class="py-2 ">Não tem conta? <a href="/cadastrar">Cadastre-se</a></p>
                </div>

            </div>
    
        </div>
    </div>
</div>