<div class="container bg-white direct border">
    <div class="">
        <div class="row">
            <div class="col-4">
                <div class="border-bottom">
                    <p class="text-center">Direct</p>
                    <a href="#"><img src="" alt=""></a>
                </div>
                <div>
                    <p>Mensagens</p>
                    <div class="inbox_usuario row">
                        <div class="col-2"><img src="" alt=""></div>
                        <div class="col"><p>Nome do usuáario</p></div>
                    </div>
                </div>
            </div>
            <div class="text-center chat col-8 d-flex flex-column justify-content-center align-items-center">
                <div class="mx-auto d-block "><img src="img/direct.png" alt="direct" class=" p-1 my-4 "></div>
                <h4>Suas mensagens</h4>
            </div>
            <!--
            <div class="col-8 border-left">
                <div class="row border-bottom">
                    <div class="col-1"><img src="" alt="foto_perfil"></div>
                    <div class="col-4"><p>Nome do usuário</p></div>
                </div>
                
                <form action="">
                    <input type="text" placeholder="Mensagem" name="mensagem" class="form-control">
                </form>
            </div>-->
        </div> 

    </div>
</div>