<div class="container bg-white direct border">
    <div class="">
        <div class="row users">
            <div class="col-4">
                <div class="text-center p-3">
                    <p class=" d-inline mb-4">Direct</p>
                    <a href="#" class="d-inline float-right mb-4"><img src="img/edit.png" alt=""></a>
                </div>
                <div class="border-top">
                    <p>Mensagens</p>
                    <div class="inbox_usuario row">
                        <div class="col-2"><img src="" alt=""></div>
                        <div class="col"><p>Nome do usuáario</p></div>
                    </div>
                </div>
            </div>
            <div class="text-center border-left chat col-8 d-flex flex-column justify-content-center align-items-center">
                <div class="mx-auto d-block "><img src="img/direct.png" alt="direct" class=" p-1 my-4 "></div>
                <h4>Suas mensagens</h4>
                <small>Envie fotos e mensagens privadas para um amigo ou grupo.</small>
                <button class="btn btn-primary mt-3">Enviar mensagens</button>
            </div>
            <!--
            <div class="col-8 border-left">
                <div class="row border-bottom">
                    <div class="col-1"><img src="" alt="foto_perfil"></div>
                    <div class="col-4"><p>Nome do usuário</p></div>
                </div>
                
                <form action="">
                    <input type="text" placeholder="Mensagem" name="mensagem" class="form-control">
                </form>
            </div>-->
        </div> 

    </div>
</div>