<section class="pagina_perfil ">
    <div class="container-fluid mx-auto pagina_perfil_container">
        <div class="container" aling="center">
            <div class="row pt-4 align-items-center">
                <div class="col-4">
                    <a href="#"><div class="pb-5"><img class="rounded-circle" id="foto_perfil_perfil" src="img/perfil.jpg" alt="perfil"></div></a>
                </div>
    
                <div class="col-8">
                    <div class="">
                        <h4 class="d-inline text-secondary"><?= $this->view->info_usuario['usuario']?></h4>
                        <button class="btn btn-light border d-inline ml-3">Editar perfil</button>
                        <a class="nav-link dropdown d-inline" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img class="img_config ml-3" src="img/config.png"></a>
                        <ul class="text-right">
                            <div class="dropdown-menu config_perfil">
                                <a class="dropdown-item" href="#">Alterar senha</a>
                                <a class="dropdown-item" href="/sair">Sair</a>
                                <a class="dropdown-item" href="#">Cancelar</a>
                            </div>
                        </ul>
    
                    </div>
                    <div class="mt-2 info_seguir">
                        <a class="d-inline">0 publicações</a>
                        <a class="d-inline ml-2">0 seguidores</a>
                        <a class="d-inline ml-2">0 seguindo</a>
                    </div>
                    <div class="mt-4 info_bio">
                        <p><?= $this->view->info_usuario['nome']?></p>
                        <p>Não precisa inovar muito para atrair mais atenção de seus seguidores. Muitas vezes </p>
                        <a href="#" class="text-primary">LinkBio</a>
                    </div>
                </div>
            </div>
            
        </div>
        <hr>
                <div class="posts_perfil text-center">
                    <a href="#" class="text-secondary"><img src="img/publication.png" alt="">  PUBLICAÇÕES</a>
                </div>
                
                <div class="mt-3   row">
                    
                    <?php foreach($this->view->posts as $id_post => $post){ ?>
                        <div class="col-4">
                            <a href="#" class="mb-4 d-block"><img class="posts_galeria img-fluid" src="uploads/<?=$post['imagem']?>" alt=""></a>
                        </div>
                    <?php } ?>
                </div>
                
    </div>
</section>

