<section class="pagina_perfil ">
    <div class="container-fluid mx-auto">
        <div class="container" aling="center">
            <div class="row pt-4 align-items-center">
                <div class="col-4">
                    <a href="#"><div class="pb-5"><img class="rounded-circle" id="foto_perfil_perfil" src="img/perfil.jpg" alt="perfil"></div></a>
                </div>
    
                <div class="col-8">
                    <div class="">
                        <h4 class="d-inline text-secondary">gabriel</h4>
                        <button class="btn btn-light border d-inline ml-3">Editar perfil</button>
                        <a class="nav-link dropdown d-inline" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img class="img_config ml-3" src="img/config.png"></a>
                        <ul class="text-right">
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </ul>
    
                    </div>
                    <div class="mt-2 info_seguir">
                        <a class="d-inline">0 publicações</a>
                        <a class="d-inline ml-2">0 seguidores</a>
                        <a class="d-inline ml-2">0 seguindo</a>
                    </div>
                    <div class="mt-4 info_bio">
                        <p>Gabriel Santos</p>
                        <p>Não precisa inovar muito para atrair mais atenção de seus seguidores. Muitas vezes </p>
                        <a href="#" class="text-primary">LinkBio</a>
                    </div>
                </div>
            </div>
            
        </div>
        <hr>
                <div class="posts_perfil text-center">
                    <a href="#" class="text-secondary"><img src="img/publication.png" alt="">  PUBLICAÇÕES</a>
                </div>
                
                <div class="mt-3   row">
                    <div class="col-4">
                        <a href="#" class="mb-4 d-block"><img class="posts_galeria img-fluid" src="img/perfil.jpg" alt=""></a>
                    </div>
                    <div class="col-4">
                        <a href="#" class="mb-4 d-block"><img class="posts_galeria img-fluid" src="img/perfil.jpg" alt=""></a>
                    </div>
                    <div class="col-4">
                        <a href="#" class="mb-4 d-block"><img class="posts_galeria img-fluid" src="img/perfil.jpg" alt=""></a>
                    </div>
                    <div class="col-4">
                        <a href="#" class="mb-4 d-block"><img class="posts_galeria img-fluid" src="img/perfil.jpg" alt=""></a>
                    </div>
                </div>
                <!-- Page galeria -->
                <div class="">
    
                <div class="row text-center text-lg-left">
    
                <div class="col-lg-4 col-md-4 col-4">
                    <a href="#" class="d-block mb-4 h-200">
                        <img class="img-fluid" src="https://source.unsplash.com/pWkk7iiCoDM/400x300" alt="">
                        </a>
                </div>
                <div class="col-lg-4 col-md-4 col-4">
                    <a href="#" class="d-block mb-4 h-200">
                        <img class="img-fluid " src="https://source.unsplash.com/aob0ukAYfuI/400x300" alt="">
                        </a>
                </div>
                <div class="col-lg-4 col-md-4 col-4">
                    <a href="#" class="d-block mb-4 h-200">
                        <img class="img-fluid " src="https://source.unsplash.com/EUfxH-pze7s/400x300" alt="">
                        </a>
                </div>
                <div class="col-lg-4 col-md-4 col-4">
                    <a href="#" class="d-block mb-4 h-200">
                        <img class="img-fluid " src="https://source.unsplash.com/M185_qYH8vg/400x300" alt="">
                        </a>
                </div>
                <div class="col-lg-4 col-md-4 col-4">
                    <a href="#" class="d-block mb-4 h-200">
                        <img class="img-fluid " src="https://source.unsplash.com/sesveuG_rNo/400x300" alt="">
                        </a>
                </div>
                <div class="col-lg-4 col-md-4 col-4">
                    <a href="#" class="d-block mb-4 h-200">
                        <img class="img-fluid " src="https://source.unsplash.com/AvhMzHwiE_0/400x300" alt="">
                        </a>
                </div>
                
                </div>
    
                </div>
                <!-- /.galeria -->
    </div>
</section>

