
<section class="d-flex justify-content-center flex-container" aling="center" id="pagina_home">
    <div class="align-items-center">
        <div class="text-center">

            <!-- Button trigger modal -->
            <button type="button" class="btn mt-3" data-toggle="modal" data-target="#exampleModal">
            <img src="img/adicionar.png" class="botaoAddPost">
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Adicionar post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                        <div class="modal-body">

                            <form action="/post" method="post" enctype="multipart/form-data">
                                <div class="d-flex justify-content-center">
                                    <div class="post align-items-center">
                                        <div class="upload">
                                            <div class="inputFileOverlay">Selecione a imagem</div>
                                            <input required type="file" id="img_post" name="img_post" accept="image/png, image/jpeg"  />
                                        </div>
                                    </div>
                                </div>  
                                <div class="addComentario">
                                    <div class="input-group mb-3 mt-3">
                                        <input name="post" type="text" class="form-control" placeholder="Descrição..." >
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                    <input type="submit" nome="postar" value="Postar" class="btn btn-success"></input>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php foreach($this->view->posts as $id_post => $post){ ?>
        <div class="mt-2 border post">
            <div class="row mt-2 container">
                <div class=" col-1 ">
                    <a href="#"><img class="rounded-circle border foto_perfil_post" id="foto_perfil_timeline" src="<?= $this->view->info_usuario['foto_perfil']?>" alt="perfil"></a>
                </div>
                <div class="col-10 ">
                    <p><?=$post['usuario']?></p>
                </div>
                <div class="col-1 conf_post">
                    <ul class="nav text-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img src="img/pontos.png" alt="opções"></a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                    
                </div>
            </div>
            <hr class="my-0">
            <div class="">
                <img src="uploads/<?=$post['imagem']?>" class="postagem  mx-auto d-block" alt="postagem">
                <div class="ml-2">
                    <div class="row">
                        <div class="col-1">
                        <!-- Se o usuário não curtiu o post mostrar o caração branco se curtiu mostrar o vermelho -->
                        <?php if($post['curtida'] == 0){ ?>
                            <a  ><img id="curtir"  onclick="curtir(<?=$post['id']?>, 'curtir', this.getAttribute('src'))" src="img/coracao.png"></a>
                        <?php } else if($post['curtida'] == 1){ ?>
                            <a  ><img id="curtir"  onclick="curtir(<?=$post['id']?>, 'descurtir', this.getAttribute('src'))" src="img/coracao_vermelho.png"></a>
                        <?php } ?>

                            <div id="resultado_test"></div>
                        </div>
                        <div class="col-1">
                            <a href=""><img src="img/comentario.png"></a>
                            <div id="resultado_test"></div>
                        </div>
                    </div>
                    <p class="">Curtido por <?= $post['curtidas']?> pessoas</p>

                    <div class="descricao">
                        <p><strong><?=$post['usuario']?></strong> <?=$post['post']?></p>
                    </div>

                    <div class="hora">
                        <small class="text-secondary">
                            <?php 
                                $data_post = $post['data_post'];

                                if($data_post < 60){
                                    echo "HÁ ".floor($data_post) . " SEGUNDOS";
                                }
                                else if($data_post >= 60 && $data_post < 3600){
                                    $data_post = $data_post / 60;
                                    echo "HÁ ".floor($data_post) . " MINUTOS";
                                }
                                else if($data_post >= 3600 && $data_post < 86400){
                                    $data_post = $data_post / 3600;
                                    echo "HÁ ". floor($data_post) . " HORAS";
                                }
                                else if($data_post >= 86400 && $data_post < 604800){
                                    $data_post = $data_post / 86400;
                                    echo "HÁ ". floor($data_post) . " DIAS";
                                }
                                else if($data_post >= 604800){
                                    $data_post = $data_post / 86400;
                                    echo "HÁ ". floor($data_post) . " DIAS";
                                }
                                
                                //$data_atual = new DateTime();
                                //$data_atual->format('d-m-Y H:i:s');
                                //$tempo_post =  $data_atual->format('d-m-Y H:i:s') - $data_post;
                                
                            
                            ?>
                        </small>
                    </div>
                    <hr class="ml-none">

                    <div class="addComentario">
                        <div class="input-group mb-3">
                            <input type="text" id="comentar" class="form-control" placeholder="Adicione um comentário..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-primary" onclick="comentar(<?= $post['id'] ?>)" type="button">Publicar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <img src="">
            </div>
        </div>
        <?php } ?>

    </div>
</section>