<header>
    <div class="row text-center mt-3">
        <div class="col-4">
            <a href=""><img class="img-fluid " id="logo_timiline" src="/img/instagram.png"></a>
        </div>
        <div class="col-4">
            <div cla="form-group input-group">
                <input type="text" class="form-group" nome="pesquisar" id="pesquisar" placeholder="Pesquisar"></input>

            </div>
        </div>
        <div class="col-4">
            <a href=""><img src="/img/home.png"></a>
            <a href=""><img src="/img/home.png"></a>
            <a href=""><img src="/img/home.png"></a>
            <a href=""><img src="/img/home.png"></a>
            <a href=""><img src="/img/home.png"></a>
        </div>
    </div>
    <hr>
</header>