<header class="fixed-top bg-white head">
    <div class="row text-center mt-3">
        <div class="col-3">
            <a href=""><img alt="Instagram" class="img-fluid " id="logo_timiline" src="/img/instagram.png"></a>
        </div>
        <div class="col-4">
            <fomr action="pesquisarUsuario" method="get">
                <div class="input-group input_pesquisa mx-auto">
                        <input onkeyup="getDados();" type="text" class="form-control pesquisa" id="pesquisar" nome="usuario" placeholder="Search">
                    <div class="input-group-append">
                        <a class="btn-sm btn-secondary" ><img src="img/pesquisar.png" alt="pesquisar"></a>
                    </div>
                </div>
            </form>
            <div id="Resultado" class="resultado_pesquisa center mt-2"></div>
        </div>
        <div class="col-5 home_icones ">
    
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="#"><img src="/img/home.png" alt="Home"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><img src="/img/enviar.png" alt="Enviar"></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><img src="/img/coracao.png" alt="Curtidas"></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img class="rounded-circle border" src="img/perfil.png" alt="perfil"></a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="#">Ação</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                        <a class="dropdown-item" href="/sair">Sair</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <hr>
</header>


<section class="d-flex justify-content-center" aling="center" id="pagina_home">
    <div class="align-items-center">
        <div class="text-center">

            <!-- Button trigger modal -->
            <button type="button" class="btn mt-5" data-toggle="modal" data-target="#exampleModal">
            <img src="img/adicionar.png" class="botaoAddPost">
            </button>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Adicionar post</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                        <div class="modal-body">

                            <form action="/post" method="post" enctype="multipart/form-data">
                                <div class="d-flex justify-content-center">
                                    <div class="post align-items-center">
                                        <div class="upload">
                                            <div class="inputFileOverlay">Selecione a imagem</div>
                                            <input required type="file" id="img_post" name="img_post" accept="image/png, image/jpeg"  />
                                        </div>
                                    </div>
                                </div>  
                                <div class="addComentario">
                                    <div class="input-group mb-3 mt-3">
                                        <input name="post" type="text" class="form-control" placeholder="Descrição..." >
                                    </div>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                    <input type="submit" nome="postar" value="Postar" class="btn btn-success"></input>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php foreach($this->view->posts as $id_post => $post){ ?>
        <div class="mt-2 border post">
            <div class="row mt-2">
                <div class="ml-2 col-1 start">
                    <a href="#"><img class="rounded-circle border" src="img/perfil.png" alt="perfil"></a>
                </div>
                <div class="col-3 start">
                    <p><?=$post['usuario']?></p>
                </div>
                <div class="col-7 mt-2">
                    <ul class="nav text-right">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><img src="img/pontos.png" alt="opções"></a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                    
                </div>
            </div>

            <div class="">
                <img src="uploads/<?=$post['imagem']?>" class="postagem" alt="postagem">
                <div class="ml-2">
                    <div class="row">
                        <div class="col-1">
                            <a href="#"><img id="curtir"  onclick="curtir(this)" src="img/coracao.png"></a>
                        </div>
                        <div class="col-1">
                            <a href="#"><img src="img/comentario.png"></a>
                        </div>
                    </div>
                    <p class="">Curtido por 3 pessoas</p>

                    <div class="descricao">
                        <p><strong><?=$post['usuario']?></strong> <?=$post['post']?></p>
                    </div>

                    <div class="hora">
                        <small class="text-secondary">
                            <?php 
                                $data_post = $post['data_post'];

                                if($data_post < 60){
                                    echo "HÁ ".floor($data_post) . " SEGUNDOS";
                                }
                                else if($data_post >= 60 && $data_post < 3600){
                                    $data_post = $data_post / 60;
                                    echo "HÁ ".floor($data_post) . " MINUTOS";
                                }
                                else if($data_post >= 3600 && $data_post < 86400){
                                    $data_post = $data_post / 3600;
                                    echo "HÁ ". floor($data_post) . " HORAS";
                                }
                                else if($data_post >= 86400 && $data_post < 604800){
                                    $data_post = $data_post / 86400;
                                    echo "HÁ ". floor($data_post) . " DIAS";
                                }
                                
                                //$data_atual = new DateTime();
                                //$data_atual->format('d-m-Y H:i:s');
                                //$tempo_post =  $data_atual->format('d-m-Y H:i:s') - $data_post;
                                
                            
                            ?>
                        </small>
                    </div>
                    <hr class="ml-none">

                    <div class="addComentario">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Adicione um comentário..." aria-label="Recipient's username" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-primary" type="button">Publicar</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div>
                <img src="">
            </div>
        </div>
        <?php } ?>

    </div>
</section>