<div class="container bg-white direct border">
    <div class="">
        <div class="row users">
            <div class="col-4">
                <div class="text-center p-3 border-bottom">
                    <p class=" d-inline mb-4">Direct</p>
                    <a href="#" class="d-inline float-right mb-4" data-toggle="modal" data-target="#exampleModal"><img src="img/edit.png" alt=""></a>
                </div>
                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Nova Mensagem</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>Sugestões</p>
                            <fomr action="pesquisarUsuario" method="get">
                                <div class="input-group input_pesquisa mx-auto">
                                    <label for="usuario">Para: </label>
                                    <input onkeyup="getDados();" type="text" class="form-control pesquisa" id="pesquisar" nome="usuario" placeholder="Search">
                                </div>
                                <hr>
						    </form>
                            <div class="container">
                                <a href="#"><img src=""></a>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                        </div>
                    </div>
                </div>
                <p>Mensagens</p>
                <div class="inbox_usuario">
                    <a href="#">
                        <div class=" row mt-3">
                            <div class="col-2"><img src="img_perfil/padrao.jpg" class="rounded-circle foto_perfil_edit" alt=""></div>
                            <div class="col"><p>Gabriel</p></div>
                        </div>
                        <small>Online há 3 h</small>
                    </a>
                </div>
                <div class="inbox_usuario">
                    <a href="#">
                        <div class=" row mt-3">
                            <div class="col-2"><img src="img_perfil/padrao.jpg" class="rounded-circle foto_perfil_edit" alt=""></div>
                            <div class="col"><p>Gabriel</p></div>
                        </div>
                        <small>Online há 3 h</small>
                    </a>
                </div>
                <div class="inbox_usuario">
                    <a href="#">
                        <div class=" row mt-3">
                            <div class="col-2"><img src="img_perfil/padrao.jpg" class="rounded-circle foto_perfil_edit" alt=""></div>
                            <div class="col"><p>Gabriel</p></div>
                        </div>
                        <small>Online há 3 h</small>
                    </a>
                </div>
                
            </div>
            <!-- Condição para apresentar a conversa apenas se o usuário estiver selecionado -->
            <!-- 

                <div class="text-center border-left chat col-8 d-flex flex-column justify-content-center align-items-center">
                    <div class="mx-auto d-block"><img src="img/direct.png" alt="direct" class=" p-1 my-4 "></div>
                    <h4>Suas mensagens</h4>
                    <small>Envie fotos e mensagens privadas para um amigo ou grupo.</small>
                    <button class="btn btn-primary mt-3">Enviar mensagens</button>
                </div>
             -->
            
            <div class="col-8 p-3 border-left">
                <div class="row border-bottom">
                    <div class="col-1"><img src="img_perfil/padrao.jpg" class="rounded-circle foto_perfil_edit" alt=""></div>
                    <div class="col-4"><p>Gabriel</p></div>
                </div>
                <div class="area_mensagens">

                </div>
                <form action="/enviarMensagem" method="POST">
                    <div class="input-group mb-3 border form_mensagem ">
                        <input type="text"  data-emojiable="true" onkeypress="enviar()" placeholder="Mensagem" id="mensagem" name="mensagem" class="form-control mensagem pl-5">
                            <div class="input-group-append">
                                <button class="btn"  id="enviar" type="submit">Enviar</button>
                            </div>
                    </div>
                </form>
                
            </div>
        </div> 

    </div>
</div>