<html>
	<head>
		<meta charset="utf-8" />
		<title><?php 
			if($this->view->info_usuario['usuario'] != '' && $this->view->info_usuario['nome'] != ''){
				echo $this->view->info_usuario['nome'] . " (@" .$this->view->info_usuario['usuario'] . ")";
			}
			else{
				echo "Instagram clone";
			}
		?></title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">

		<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
		<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
		<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

		
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
		

		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<script src="js/main.js"></script>
		<script src="js/ajax.js"></script>
	</head>

	<body>
		<header class="fixed-top bg-white border-bottom">
			<div class="container mx-auto" aling="center">
				<div class="row mt-2 mb-2 align-items-center">
					<div class="col-2">
						<a href="/timeline"><img alt="Instagram" class="" id="logo_timiline" src="/img/instagram.png"></a>
					</div>
					<div class="col-5">
						<fomr action="pesquisarUsuario" method="get">
							<div class="input-group input_pesquisa mx-auto">
									<input onkeyup="getDados();" type="text" class="form-control pesquisa" id="pesquisar" nome="usuario" placeholder="Search">
								<div class="input-group-append">
									<a class="btn-sm btn-secondary" ><img src="img/pesquisar.png" alt="pesquisar"></a>
								</div>
							</div>
						</form>
						<div id="Resultado" class="resultado_pesquisa mt-2"></div>
					</div>
					<div class="home_icones col-5 d-flex justify-content-end end">
						<ul class="nav">
							<li class="nav-item">
								<a class="nav-link " href="#"><img src="/img/home.png" alt="Home"></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#"><img src="/img/enviar.png" alt="Enviar"></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#"><img src="/img/coracao.png" alt="Curtidas"></a>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link" href="/perfil" role="button" ><img class="rounded-circle border" src="img/perfil.png" alt="perfil"></a>
								
							</li>
						</ul>
					</div>
				</div>
			</div>
		</header>
		

		<?= $this->content() ?>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
	</body>

</html>